sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - docker build -t bgruening/docker-jupyter-notebook .
  - |
    docker run -d -p 8888:8888 bgruening/docker-jupyter-notebook
  - docker ps

script:
  - curl --fail http://localhost:8888/ipython/notebooks
