sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - docker build -t jupyter_galaxy .
  - |
    docker run -d -p 8888:8888 jupyter_galaxy
  - docker ps


script:
  - curl --fail http://localhost:8888/ipython/notebooks
